# Generated by Django 5.2 on 2026-01-06 09:55

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название карго')),
                ('manager_contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт менеджера')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип карго')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Иконка карго')),
                ('telegram_token', models.CharField(blank=True, max_length=255, verbose_name='Токен телеграм')),
                ('telegram_bot_username', models.CharField(blank=True, max_length=255, verbose_name='Username бота')),
                ('currency', models.CharField(blank=True, default='KGS', max_length=16, verbose_name='Валюта')),
                ('default_price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена по умолчанию за кг')),
                ('is_site_enabled', models.BooleanField(default=True, verbose_name='Сайт включен')),
                ('is_bot_enabled', models.BooleanField(default=True, verbose_name='Бот включен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
