# Generated by Django 5.2 on 2026-01-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=255, verbose_name='ID администратора')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='base.settings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'ID администратора',
                'verbose_name_plural': 'ID администраторов',
            },
        ),
    ]
