# Generated by Django 5.2 on 2026-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_adminid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Основные настройка', 'verbose_name_plural': '2) Основные настройки'},
        ),
        migrations.AddField(
            model_name='settings',
            name='registration_webapp_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на регистрацию (Telegram WebApp)'),
        ),
    ]
