# Generated by Django 5.2 on 2026-01-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Основные настройка', 'verbose_name_plural': '1) Основные настройки'},
        ),
    ]
