# Generated by Django 5.2 on 2026-01-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name', 'country', 'city'], 'verbose_name': '2) Склад', 'verbose_name_plural': '2) Склады'},
        ),
    ]
