# Generated by Django 5.2 on 2026-01-10 01:34

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Инструкция')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='instructions/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': '3) Инструкция',
                'verbose_name_plural': '3) Инструкции',
                'ordering': ['-created_at'],
            },
        ),
    ]
