# Generated by Django 5.2 on 2026-01-10 02:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='prohibited_goods_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Запрещенные товары (текст)'),
        ),
    ]
