# Generated by Django 5.2 on 2026-01-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_settings_prohibited_goods_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
    ]
