# Generated by Django 5.2 on 2026-01-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_settings_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pvz_location_url',
            field=models.URLField(blank=True, verbose_name='Локация ПВЗ (ссылка на карту)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='work_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Режим работы'),
        ),
    ]
