# Generated by Django 5.2 on 2026-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_filial_wholesale_whatsapp_and_textfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='work_hours',
            field=models.TextField(blank=True, verbose_name='Режим работы'),
        ),
    ]
