# Generated by Django 5.2 on 2026-01-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_filial_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='storage_penalty_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Штраф за хранение (в день)'),
        ),
    ]
