# Generated by Django 5.2 on 2026-01-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_user_delete_registrationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '1) Пользователи', 'verbose_name_plural': '1) Пользователи'},
        ),
    ]
