# Generated by Django 5.2 on 2026-01-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name', 'country', 'city'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='user',
            name='client_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код клиента'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_type',
            field=models.CharField(blank=True, choices=[('individual', 'Физ. лицо'), ('business', 'Бизнес')], max_length=16, null=True, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общий долг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Код языка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('client_registered', 'Клиент (Зарегистрирован)')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=128, verbose_name='Трек-номер')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес (кг)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за кг')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_china', 'В Китае'), ('on_the_way', 'В пути'), ('arrived', 'Прибыл'), ('delivered', 'Доставлен'), ('not_picked', 'Не забрали')], default='created', max_length=32, verbose_name='Статус')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='telegram_bot.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=16, verbose_name='Метод')),
                ('paid_at', models.DateTimeField(verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='telegram_bot.user', verbose_name='Клиент')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='telegram_bot.shipment', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('operator', 'Оператор'), ('manager', 'Менеджер')], max_length=16, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['role', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoragePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_days', models.PositiveSmallIntegerField(default=3, verbose_name='Бесплатные дни')),
                ('penalty_per_day', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Штраф за день')),
                ('days_overdue', models.PositiveIntegerField(verbose_name='Просрочено дней')),
                ('total_penalty', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итоговый штраф')),
                ('calculated_at', models.DateTimeField(verbose_name='Рассчитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_penalty', to='telegram_bot.shipment', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Штраф за хранение',
                'verbose_name_plural': 'Штрафы за хранение',
                'ordering': ['-calculated_at', '-created_at'],
            },
        ),
    ]
