# Generated by Django 5.2 on 2026-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_warehouse_alter_user_options_user_client_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Цена за кг'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='Вес (кг)'),
        ),
    ]
