# Generated by Django 5.2 on 2026-01-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_filial"),
        ("telegram_bot", "0006_user_filial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client_status",
            field=models.CharField(
                choices=[("new", "Новый"), ("old", "Старый")],
                default="new",
                max_length=16,
                verbose_name="Статус клиента",
            ),
        ),
        migrations.CreateModel(
            name="PreClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(max_length=32, unique=True, verbose_name="Код клиента"),
                ),
                ("phone", models.CharField(max_length=64, verbose_name="Телефон")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preclients",
                        to="base.filial",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преддобавленный клиент",
                "verbose_name_plural": "Преддобавленные клиенты",
                "ordering": ["-created_at"],
            },
        ),
    ]
