# Generated by Django 5.2 on 2026-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0007_preclient_and_user_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="Telegram ID"),
        ),
    ]
