# Generated by Django 5.2 on 2026-01-11 16:16

from django.db import migrations, models
from django.db.models import Q


def set_default_client_type(apps, schema_editor):
    User = apps.get_model("telegram_bot", "User")
    User.objects.filter(Q(client_type__isnull=True) | Q(client_type="")).update(client_type="individual")


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0008_alter_user_telegram_id_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[("individual", "Физ. лицо"), ("business", "Бизнес")],
                default="individual",
                max_length=16,
                null=True,
                verbose_name="Тип клиента",
            ),
        ),
        migrations.RunPython(set_default_client_type, migrations.RunPython.noop),
    ]
