# Generated by Django 5.2 on 2026-01-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_user_client_type_default_individual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreClient',
        ),
    ]
