# Generated by Django 5.2 on 2026-01-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_delete_preclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('operator', 'Оператор'), ('manager', 'Менеджер'), ('director', 'Директор')], max_length=16, verbose_name='Роль'),
        ),
    ]
