# Generated by Django 5.2 on 2026-01-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_staff_role'),
        ('telegram_bot', '0011_staff_role_director'),
    ]

    operations = [
    ]
