# Generated by Django 5.2 on 2026-01-11 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0012_merge_0011_alter_staff_role_0011_staff_role_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersSH",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Менеджер"), ("director", "Директор")],
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userssh_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штатный",
                "verbose_name_plural": "Штатные",
                "ordering": ["role", "-created_at"],
            },
        ),
        migrations.DeleteModel(name="Notification"),
        migrations.DeleteModel(name="StoragePenalty"),
        migrations.DeleteModel(name="Payment"),
        migrations.DeleteModel(name="Staff"),
    ]
