# Generated by Django 5.2 on 2026-01-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0013_remove_unused_models_add_userssh"),
    ]

    operations = [
        migrations.DeleteModel(name="UsersSH"),
        migrations.CreateModel(
            name="UsersSH",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Менеджер"), ("director", "Директор")],
                        max_length=16,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штатный",
                "verbose_name_plural": "Штатные",
                "ordering": ["role", "-date_joined"],
            },
            bases=(settings.AUTH_USER_MODEL,),
        ),
    ]
