# Generated by Django 5.2 on 2026-01-11 21:45

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_userssh_inherits_auth_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userssh',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
