# Generated by Django 5.2 on 2026-01-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_shipment_groups_and_import_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('in_china', 'В Китае'), ('on_the_way', 'В пути'), ('bishkek', 'В Бишкеке'), ('warehouse', 'На складе'), ('issued', 'Выдано'), ('arrived', 'Прибыл'), ('delivered', 'Доставлен'), ('not_picked', 'Не забрали')], default='created', max_length=32, verbose_name='Статус'),
        ),
    ]
