# Generated by Django 5.2 on 2026-01-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='storage_penalty_last_charged_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего начисления штрафа'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='storage_penalty_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Штраф за хранение (итого)'),
        ),
    ]
