# Generated by Django 5.2 on 2026-01-13 00:00

from django.db import migrations, models
import django.db.models.deletion


def backfill_filial(apps, schema_editor):
    Filial = apps.get_model("base", "Filial")
    User = apps.get_model("telegram_bot", "User")
    Shipment = apps.get_model("telegram_bot", "Shipment")
    ShipmentGroup = apps.get_model("telegram_bot", "ShipmentGroup")

    # Backfill shipments.filial from user.filial
    for sh in Shipment.objects.select_related("user").all():
        if sh.filial_id is not None:
            continue
        user = getattr(sh, "user", None)
        filial_id = getattr(user, "filial_id", None) if user is not None else None
        if filial_id is not None:
            Shipment.objects.filter(id=sh.id).update(filial_id=filial_id)

    # Backfill groups.filial from first shipment.filial in that group
    for g in ShipmentGroup.objects.all():
        if g.filial_id is not None:
            continue
        filial_id = (
            Shipment.objects.filter(group_id=g.id)
            .exclude(filial_id__isnull=True)
            .values_list("filial_id", flat=True)
            .first()
        )
        if filial_id is not None:
            ShipmentGroup.objects.filter(id=g.id).update(filial_id=filial_id)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_filial_storage_penalty_per_day"),
        ("telegram_bot", "0018_shipment_storage_penalty_last_charged_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userssh",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="base.filial",
                verbose_name="Филиал",
            ),
        ),
        migrations.AddField(
            model_name="shipmentgroup",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_groups",
                to="base.filial",
                verbose_name="Филиал",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="base.filial",
                verbose_name="Филиал",
            ),
        ),
        migrations.RunPython(backfill_filial, reverse_code=noop_reverse),
    ]
