# Generated by Django 5.2 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0019_filial_isolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentgroup",
            name="sent_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата отправки"),
        ),
    ]
