# Generated by Django 5.2 on 2026-01-14 00:00

from django.db import migrations


def map_old_statuses(apps, schema_editor):
    Shipment = apps.get_model("telegram_bot", "Shipment")

    allowed = {"on_the_way", "bishkek", "warehouse", "issued"}

    # Anything outside the allowed set is mapped to "on_the_way"
    qs = Shipment.objects.exclude(status__in=list(allowed))
    qs.update(status="on_the_way")


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0020_shipmentgroup_sent_date"),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, reverse_code=noop_reverse),
    ]
