# Generated by Django 5.2 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0021_map_old_shipment_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentgroup",
            name="bishkek_marked",
            field=models.BooleanField(default=False, verbose_name="Отмечено: В Бишкеке"),
        ),
    ]
