# Generated by Django 5.2 on 2026-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_shipmentgroup_bishkek_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'В пути'), ('bishkek', 'В Бишкеке'), ('warehouse', 'Готов к выдаче'), ('issued', 'Выдано')], default='on_the_way', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='shipmentgroup',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'В пути'), ('bishkek', 'В Бишкеке'), ('warehouse', 'Готов к выдаче'), ('issued', 'Выдано')], default='on_the_way', max_length=32, verbose_name='Статус группы'),
        ),
    ]
