# Generated by Django 5.2 on 2026-01-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0023_alter_shipment_status_alter_shipmentgroup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_penalty_last_charged_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего начисления штрафа"),
        ),
        migrations.AddField(
            model_name="user",
            name="storage_penalty_total",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name="Штраф за хранение (итого)"),
        ),
    ]
