# Generated by Django 5.2 on 2026-01-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0024_user_storage_penalty_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="pricing_mode",
            field=models.CharField(choices=[("kg", "По кг"), ("gabarit", "По габариту")], default="kg", max_length=16, verbose_name="Способ расчёта"),
        ),
    ]
