# Generated by Django 5.2 on 2026-01-24 00:00

from django.db import migrations, models
from django.db.models import F


def _backfill_issued_at(apps, schema_editor):
    Shipment = apps.get_model("telegram_bot", "Shipment")
    Shipment.objects.filter(status="issued", issued_at__isnull=True).update(issued_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0025_shipment_pricing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
        migrations.RunPython(_backfill_issued_at, migrations.RunPython.noop),
    ]
