from django.urls import path

from . import views

urlpatterns = [
    path("manager/login/", views.manager_login, name="manager_login"),
    path("manager/logout/", views.manager_logout, name="manager_logout"),
    path("manager/notifications/", views.manager_notifications, name="manager_notifications"),
    path("manager/notifications/broadcast/", views.manager_notifications_broadcast, name="manager_notifications_broadcast"),
    path("manager/notifications/penalty-remind/", views.manager_notifications_penalty_remind, name="manager_notifications_penalty_remind"),
    path("manager/notifications/ready-remind/", views.manager_notifications_ready_remind, name="manager_notifications_ready_remind"),
    path("manager/", views.manager_dashboard, name="manager_dashboard"),
    path("manager/analytics/", views.manager_analytics, name="manager_analytics"),
    path("manager/sorting/", views.manager_sorting, name="manager_sorting"),
    path("manager/penalties/", views.manager_penalties, name="manager_penalties"),
    path("manager/clients/", views.manager_clients, name="manager_clients"),
    path("manager/clients/<int:user_id>/", views.manager_client_detail, name="manager_client_detail"),
    path("manager/clients/<int:user_id>/debt/clear/", views.manager_client_debt_clear, name="manager_client_debt_clear"),
    path(
        "manager/clients/<int:user_id>/issue-by-tracking/",
        views.manager_client_issue_by_tracking,
        name="manager_client_issue_by_tracking",
    ),
    path(
        "manager/clients/<int:user_id>/pickup/add-by-tracking/",
        views.manager_client_pickup_add_by_tracking,
        name="manager_client_pickup_add_by_tracking",
    ),
    path(
        "manager/clients/<int:user_id>/pickup/bulk-issue/",
        views.manager_client_pickup_bulk_issue,
        name="manager_client_pickup_bulk_issue",
    ),
    path(
        "manager/clients/<int:user_id>/shipments/<int:shipment_id>/issued/",
        views.manager_client_shipment_set_issued,
        name="manager_client_shipment_set_issued",
    ),
    path("manager/clients/<int:user_id>/delete/", views.manager_client_delete, name="manager_client_delete"),
    path("manager/groups/", views.manager_groups, name="manager_groups"),
    path("manager/groups/<int:group_id>/", views.manager_group_detail, name="manager_group_detail"),
    path("manager/groups/<int:group_id>/delete/", views.manager_group_delete, name="manager_group_delete"),
    path("manager/groups/<int:group_id>/bishkek/", views.manager_group_set_bishkek, name="manager_group_set_bishkek"),
    path("manager/groups/<int:group_id>/sorting/", views.manager_group_sorting, name="manager_group_sorting"),
    path("manager/groups/<int:group_id>/shipments/<int:shipment_id>/issued/", views.manager_group_shipment_set_issued, name="manager_group_shipment_set_issued"),
    path("manager/shipments/", views.manager_shipments, name="manager_shipments"),
    path("manager/shipments/unknown/", views.manager_shipments_unknown, name="manager_shipments_unknown"),
    path("manager/shipments/client-not-found/", views.manager_shipments_client_not_found, name="manager_shipments_client_not_found"),
    path("manager/shipments/add/", views.manager_shipments_add, name="manager_shipments_add"),
    path("manager/shipments/import/", views.manager_shipments_import, name="manager_shipments_import"),
    path("manager/shipments/import-progress/<str:task_id>/", views.manager_shipments_import_progress, name="manager_shipments_import_progress"),
    path("manager/shipments/new/", views.manager_shipment_new, name="manager_shipment_new"),
    path("manager/shipments/<int:shipment_id>/", views.manager_shipment_detail, name="manager_shipment_detail"),
    path("manager/shipments/<int:shipment_id>/bishkek/", views.manager_shipment_set_bishkek, name="manager_shipment_set_bishkek"),
    path("manager/shipments/<int:shipment_id>/issued/", views.manager_shipment_set_issued, name="manager_shipment_set_issued"),
    path("manager/shipments/<int:shipment_id>/delete/", views.manager_shipment_delete, name="manager_shipment_delete"),
]
